export const INITIAL_CONTACTS = [
  {
    id: '1',
    name: 'Andre Allison',
    email: 'andre-allison@allison.hn',
    mobilePhone: '303-570-0941',
    homePhone: '543-769-0002',
    message: '@andreallison',
    jobTitle: 'Investor Implementation Analyst',
    company: 'Harvey Inc',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    favorite: true,
    frequentlyContacted: true,
    group: 'Work',
  },
  {
    id: '2',
    name: 'Allion Murphy',
    email: 'allion-murphy@aool.com',
    mobilePhone: '212-321-4567',
    homePhone: '718-456-7890',
    message: '@allionmurphy',
    jobTitle: 'Creative Director',
    company: 'Pixel Forge',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    favorite: true,
    frequentlyContacted: true,
    group: 'Most Important',
  },
  {
    id: '3',
    name: 'Ann Skinner',
    email: 'ann-skinner@shotmail.com',
    mobilePhone: '415-888-2931',
    homePhone: '510-444-1294',
    message: '@annskinner',
    jobTitle: 'Product Owner',
    company: 'Horizon Lab',
    avatarBg: 'bg-orange-500',
    favorite: false,
    frequentlyContacted: false,
    group: 'Family',
  },
  {
    id: '4',
    name: 'Brandon Leonard',
    email: 'brandon-leonard@aahoo.com',
    mobilePhone: '302-333-4455',
    homePhone: '302-999-8800',
    message: '@brandonl',
    jobTitle: 'Senior Operations Lead',
    company: 'Apex Corp',
    avatarBg: 'bg-emerald-500',
    favorite: false,
    frequentlyContacted: false,
    group: 'Projects',
  },
  {
    id: '5',
    name: 'Boris Ramirez',
    email: 'boris-ramiraz@aahoo.com',
    mobilePhone: '617-555-0192',
    homePhone: '617-555-0143',
    message: '@borisramiraz',
    jobTitle: 'Lead Devops Engineer',
    company: 'CloudScale Solutions',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    favorite: true,
    frequentlyContacted: false,
    group: 'Work',
  },
  {
    id: '6',
    name: 'Carmen Erickson',
    email: 'carmen-erickson@aool.com',
    mobilePhone: '650-811-0929',
    homePhone: '650-811-0900',
    message: '@carmene',
    jobTitle: 'Managing Partner',
    company: 'Equity First',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    favorite: false,
    frequentlyContacted: true,
    group: 'Recent Leads',
  },
  {
    id: '7',
    name: 'Carroll Hunt',
    email: 'carroll-hunt@hunt.hn',
    mobilePhone: '206-777-1234',
    homePhone: '206-888-5678',
    message: '@carrollhunt',
    jobTitle: 'Principal Recruiter',
    company: 'SearchLight Group',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&auto=format&fit=crop&q=80',
    favorite: false,
    frequentlyContacted: false,
    group: 'Work',
  },
  {
    id: '8',
    name: 'Ellen Boone',
    email: 'ellen-boone@amail.com',
    mobilePhone: '305-666-9911',
    homePhone: '305-666-9922',
    message: '@ellenboone',
    jobTitle: 'Senior Copywriter',
    company: 'WordStream',
    avatarBg: 'bg-indigo-600',
    favorite: false,
    frequentlyContacted: false,
    group: 'Family',
  },
  {
    id: '9',
    name: 'Elbert Elliott',
    email: 'elbert-elliott@liive.com',
    mobilePhone: '312-444-5555',
    homePhone: '312-444-6666',
    message: '@elbertelliott',
    jobTitle: 'Solution Architect',
    company: 'TechSustain',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    favorite: false,
    frequentlyContacted: true,
    group: 'Projects',
  },
];
